export const DESIGNS_PAGE_OPEN = 'DESIGNS_PAGE_OPEN';
export const DESIGNS_PAGE_DATA_RECEIVE = 'DESIGNS_PAGE_DATA_RECEIVE';

export const DESIGNS_PAGE_FILTERS_RECEIVE = 'DESIGNS_PAGE_FILTERS_RECEIVE';
export const DESIGNS_PAGE_GET_BATCH_DATA = 'DESIGNS_PAGE_GET_BATCH_DATA';
export const DESIGNS_PAGE_BATCH_DATA_RECEIVE = 'DESIGNS_PAGE_BATCH_DATA_RECEIVE';

export const DESIGNS_PAGE_RESET_DATA = 'DESIGNS_PAGE_RESET_DATA';

export const DESIGNS_PAGE_UPDATE_TITLE = 'DESIGNS_PAGE_UPDATE_TITLE';
export const DESIGNS_PAGE_DELETE_DESIGN = 'DESIGNS_PAGE_DELETE_DESIGN';

export const DESIGNS_PAGE_UPDATE_LIST = 'DESIGNS_PAGE_UPDATE_LIST';
export const DESIGNS_PAGE_REMOVE_LIST_ITEM = 'DESIGNS_PAGE_REMOVE_LIST_ITEM';
