export const DESIGNS_PAGE_OPEN = 'DESIGNS_PAGE_OPEN';

export const DESIGNS_PAGE_FILTERS_RECEIVE = 'DESIGNS_PAGE_FILTERS_RECEIVE';
export const DESIGNS_PAGE_GET_BATCH_DATA = 'DESIGNS_PAGE_GET_BATCH_DATA';
